
project_id = "jstwhvchwdrwkzgdfgvt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[[storage.buckets]]
name = "restaurant-assets"
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/png", "image/jpeg", "image/gif", "image/svg+xml", "image/webp"]

[[storage.buckets]]
name = "product-images"
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/png", "image/jpeg", "image/gif", "image/svg+xml", "image/webp"]

[[storage.buckets]]
name = "qrcodes"
public = true
file_size_limit = "5MB"
allowed_mime_types = ["image/png", "image/jpeg", "image/svg+xml"]
