
project_id = "jstwhvchwdrwkzgdfgvt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
check_subscription = { verify_jwt = true }
stripe_subscription = { verify_jwt = true }
