// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jstwhvchwdrwkzgdfgvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdHdodmNod2Ryd2t6Z2RmZ3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzIyMDQsImV4cCI6MjA2MTkwODIwNH0.zq0K4Jv4Gyec8sztDw2jyTM7UG0iq9Yw3GpMmSBlB84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);